name: portfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core:
  firebase_auth: ^1.1.1
  provider:
  flutter:
    sdk: flutter
  http: ^0.13.1
  json_serializable: ^4.1.1
  cupertino_icons: ^1.0.2
  multiselect_formfield: ^0.1.6

  cloud_firestore: ^1.0.6
  sms_autofill: ^1.2.6
  firebase_auth_ui: ^1.0.1
  email_auth: ^0.0.1+3
  shared_preferences: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Century Gothic
      fonts:
        - asset: assets/fonts/Century Gothic.ttf
        - asset: assets/fonts/CenturyGothic.ttf
        - asset: assets/fonts/GOTHIC.TTF
        - asset: assets/fonts/GOTHICB.TTF
        - asset: assets/fonts/GOTHICB0.TTF
        - asset: assets/fonts/GOTHICBI.TTF
        - asset: assets/fonts/GOTHICI.TTF
